version: '3'

services:
  # Service MySQL
  mysql:
    image: mysql:latest
    container_name: mysql-container1
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - microservices-network

  # Service Consul
  consul:
    image: consul:1.15.4
    container_name: consul-container
    ports:
      - "8500:8500"
    networks:
      - microservices-network

  # Service Gateway
  gateway:
    build:
      context: "/gateway"
    ports:
      - "8888:8888"
    depends_on:
      - mysql
      - consul
    networks:
      - microservices-network
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: true

  # Service Client
  client:
    build:
      context: "/client"
    ports:
      - "8088:8088"
    depends_on:
      - mysql
      - consul
      - gateway
    networks:
      - microservices-network
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: true
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientserviceDB?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100
  car:
    build:
      context: "/car"
    ports:
      - "8089-8089"
    depends_on:
      - mysql
      - consul
      - gateway
    networks:
      - microservices-network

    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED: true
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carserviceDB?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100



networks:
  microservices-network:
    driver: bridge
